import type { ListTemplate } from '../types/list.js';

/** The fixed, explicit P3-33 creation catalogue. Order is part of the contract. */
export const LIST_TEMPLATES = Object.freeze([
  {
    templateKey: 'blank',
    chooserLabel: 'Blank',
    summary: 'Start without a category or item details',
    defaultTitle: 'Untitled list',
    icon: 'list',
    itemStateMode: { mode: 'none' },
    featureConfig: {},
    slot: null,
    emptyStateCopy: 'Add the first item.',
  },
  {
    templateKey: 'checklist',
    chooserLabel: 'Checklist',
    summary: 'Items have checkboxes',
    defaultTitle: 'Checklist',
    icon: 'check-square',
    itemStateMode: { mode: 'checkbox' },
    featureConfig: {},
    slot: null,
    emptyStateCopy: 'Add something to check off.',
  },
  {
    templateKey: 'groceries',
    chooserLabel: 'Groceries',
    summary: 'A shopping checklist',
    defaultTitle: 'Groceries',
    icon: 'cart',
    itemStateMode: { mode: 'checkbox' },
    featureConfig: {},
    slot: 'groceries',
    emptyStateCopy: 'Add something to buy.',
  },
  {
    templateKey: 'watch-later',
    chooserLabel: 'Watch Later',
    summary: 'Track what to watch and episode progress',
    defaultTitle: 'Watch Later',
    icon: 'play-rect',
    itemStateMode: {
      mode: 'stages',
      labels: { open: 'Want to watch', active: 'Watching', done: 'Watched' },
      groupByState: true,
    },
    featureConfig: { progress: { enabled: true, kind: 'episode' } },
    slot: 'watch',
    emptyStateCopy: 'Add a movie or show.',
  },
  {
    templateKey: 'books-to-read',
    chooserLabel: 'Books to Read',
    summary: 'Track reading stages and progress',
    defaultTitle: 'Books to Read',
    icon: 'book',
    itemStateMode: {
      mode: 'stages',
      labels: { open: 'Want to read', active: 'Reading', done: 'Read' },
      groupByState: true,
    },
    featureConfig: { progress: { enabled: true, kind: 'text' } },
    slot: null,
    emptyStateCopy: 'Add a book to read.',
  },
  {
    templateKey: 'places-to-visit',
    chooserLabel: 'Places to Visit',
    summary: 'Save places and addresses',
    defaultTitle: 'Places to Visit',
    icon: 'map-pin',
    itemStateMode: { mode: 'checkbox' },
    featureConfig: { place: { enabled: true } },
    slot: null,
    emptyStateCopy: 'Add a place to visit.',
  },
  {
    templateKey: 'meal-ideas',
    chooserLabel: 'Meal Ideas',
    summary: 'Keep ingredients inside each meal',
    defaultTitle: 'Meal Ideas',
    icon: 'bowl',
    itemStateMode: { mode: 'none' },
    featureConfig: {
      subItems: {
        enabled: true,
        sectionLabel: 'Ingredients',
        singularLabel: 'Ingredient',
        secondaryLabel: 'Quantity',
        integration: 'mealIngredients',
      },
    },
    slot: 'meals',
    emptyStateCopy: 'Add a meal idea.',
  },
] as const satisfies readonly ListTemplate[]);
